export const frases = [
    "../Imagenes/Frases/creé-en-ti.jpg",
    "../Imagenes/Frases/no-bajes-la-meta.jpg",
    "../Imagenes/Frases/yo-puedo-y-lo-voy-a-lograr.jpg",
    "../Imagenes/Frases/amor1.jpg",
    "../Imagenes/Frases/amor2.png",
    "../Imagenes/Frases/amor3.png",
    "../Imagenes/Frases/amor4.jpg",
    "../Imagenes/Frases/amor5.jpg",
    "../Imagenes/Frases/amor6.jpg",
    "../Imagenes/Frases/amor7.jpg",
    "../Imagenes/Frases/amor8.jpg",
    "../Imagenes/Frases/amor9.jpg",
    "../Imagenes/Frases/amor10.jpg",
    "../Imagenes/Frases/amor11.jpg",
    "../Imagenes/Frases/amor12.png",
    "../Imagenes/Frases/amor13.jpg",
    "../Imagenes/Frases/amor14.jpg",
    "../Imagenes/Frases/amor15.png",
    "../Imagenes/Frases/amor16.jpg",
    "../Imagenes/Frases/amor17.jpg",
    "../Imagenes/Frases/amor18.jpg",
    "../Imagenes/Frases/amor19.jpg",
    "../Imagenes/Frases/amor20.jpg",
    "../Imagenes/Frases/descubrir1.jpg",
    "../Imagenes/Frases/descubrir2.jpg",
    "../Imagenes/Frases/descubrir3.jpg",
    "../Imagenes/Frases/descubrir4.jpg",
    "../Imagenes/Frases/descubrir5.jpg",
    "../Imagenes/Frases/descubrir7.jpg",
    "../Imagenes/Frases/descubrir8.jpg",
    "../Imagenes/Frases/descubrir9.jpg",
    "../Imagenes/Frases/descubrir10.jpg",
    "../Imagenes/Frases/descubrir11.jpg",
    "../Imagenes/Frases/descubrir12.jpg",
    "../Imagenes/Frases/descubrir13.jpg",
    "../Imagenes/Frases/descubrir14.jpg",
    "../Imagenes/Frases/descubrir15.jpg",
    "../Imagenes/Frases/descubrir16.jpg",
    "../Imagenes/Frases/descubrir17.png",
    "../Imagenes/Frases/descubrir18.jpg",
    "../Imagenes/Frases/descubrir19.png",
    "../Imagenes/Frases/descubrir20.jpg",
    "../Imagenes/Frases/superacion1.jpg",
    "../Imagenes/Frases/superacion2.jpg",
    "../Imagenes/Frases/superacion3.jpg",
    "../Imagenes/Frases/superacion4.jpg",
    "../Imagenes/Frases/superacion5.jpg",
    "../Imagenes/Frases/superacion6.jpg",
    "../Imagenes/Frases/superacion7.png",
    "../Imagenes/Frases/superacion8.jpg",
    "../Imagenes/Frases/superacion9.jpg",
    "../Imagenes/Frases/superacion10.jpg",
    "../Imagenes/Frases/superacion11.jpg",
    "../Imagenes/Frases/superacion12.jpg",
    "../Imagenes/Frases/superacion13.jpg",
    "../Imagenes/Frases/superacion14.jpg",
    "../Imagenes/Frases/superacion15.jpg",
    "../Imagenes/Frases/superacion16.png",
    "../Imagenes/Frases/superacion17.jpg",
    "../Imagenes/Frases/superacion18.jpg",
    "../Imagenes/Frases/superacion19.jpg",
    "../Imagenes/Frases/superacion20.jpg",
    "../Imagenes/Frases/superacion115.jpg"
];

export const colores = [
    "#fbe3e1",
    "#fff4ee",
    "#f1d6cd",
    "#eba0a4",
    "#ede2d4",
    "#faf6f0",
    "#f6eaec",
    "#a44c38",
    "#af4d73",
    "#e8c8c9",
    "#dee6e9",
    "#edefee",
    "#264269",
    "#deb8af",
    "#ffeaf1",
    "#ffeeec",
    "#edd0d4",
    "#efc2dd",
    "#d8b0ae",
    "#feeeef",
    "#fee1e3",
    "#d8bdc2",
    "#efd5bc",
    "#b6eaee",
    "#feddd6",
    "#0d142e",
    "#3d5772",
    "#d6f0ef",
    "#6d7faf",
    "#d0d0ea",
    "#f3e8e4",
    "#eeecf1",
    "#f9f5f2",
    "#e5e7f3",
    "#c488b5",
    "#c81a3d",
    "#303521",
    "#0c73d8",
    "#8fd9f4",
    "#fefefe",
    "#040679",
    "#333f0f",
    "#6b667d",
    "#6b667d",
    "#b7cedc",
    "#c0eff7",
    "#c4eefa",
    "#ffe8a4",
    "#ff6f69",
    "#fefefe",
    "#eae5c5",
    "#2e2f34",
    "#242c39",
    "#f4e9e5",
    "#e9c287",
    "#e0e1d1",
    "#e3c447",
    "#7d7d7a",
    "#f1ecf2",
    "#fbfbfb",
    "#ffffff",
    "#fdefec",
    "#f2ec4c"
];

// Estado actual de la frase (índice y me gusta de cada frase)
const meGustas = new Array(frases.length).fill(false);
const compartidas = new Array(frases.length).fill(false);
let indiceActual = -1;

export function getMeGustas(){
    return meGustas;
}

export function getCompartidas() {
    return compartidas;
}

export function getIndiceActual(){
    return indiceActual
}

export function setIndiceActual(nuevoIndice){
    indiceActual = nuevoIndice;
}
